version: "3.7"

services:

  wordpress:
    image: ${WORDPRESS_IMAGE_VERSION}
    container_name: ${WORDPRESS_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_MEMORY_LIMIT', '256M' );
    volumes:
      - wordpress:/var/www/html
    networks:
      - ${REVERSE_PROXY_NETWORK}
      - ${WORDPRESS_INTERNAL_NETWORK}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${REVERSE_PROXY_NETWORK}"
      - "traefik.http.routers.${WORDPRESS_ROUTER_NAME}.rule=Host(`${WORDPRESS_HOST_URL}`)"
      - "traefik.http.routers.${WORDPRESS_ROUTER_NAME}.tls.certresolver=${TLS_CERTRESOLVER}"

  mysql:
    image: ${MYSQL_IMAGE_VERSION}
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - database:/var/lib/mysql
    networks:
      - ${WORDPRESS_INTERNAL_NETWORK}
    labels:
      - "traefik.enable=false"

  phpmyadmin:
    image: ${PHPMYADMIN_IMAGE_VERSION}
    container_name: ${PHPMYADMIN_CONTAINER_NAME}
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: ${PHPMYADMIN_HOST}
      PMA_ABSOLUTE_URI: ${PHPMYADMIN_ABSOLUTE_URI}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - ${REVERSE_PROXY_NETWORK}
      - ${WORDPRESS_INTERNAL_NETWORK}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${REVERSE_PROXY_NETWORK}"
      - "traefik.http.routers.${PHPMYADMIN_ROUTER_NAME}.rule=Host(`${PHPMYADMIN_HOST_URL}`)"
      - "traefik.http.routers.${PHPMYADMIN_ROUTER_NAME}.tls.certresolver=${TLS_CERTRESOLVER}"

volumes:
  wordpress:
  database:

networks:
  reverse_proxy:
    external: true
  biborn_wp_network:
    external: false